package com.kh.samdado.mypage.model.vo;

public class Booking {
/*
 * Car
BOOKING_NO	NUMBER
BUS_NAME	VARCHAR2(100 BYTE)
PAY_NAME	VARCHAR2(100 BYTE)
BOOKING_DATE	DATE
BOOKING_MODIFY	DATE
BOOKING_ADDRESS	VARCHAR2(100 BYTE)
BOOKING_PAY	VARCHAR2(20 BYTE)
BOOKING_NUMBER	NUMBER
BOOKING_PHONE	VARCHAR2(20 BYTE)
BOOKING_TRV	DATE
US_NO	VARCHAR2(15 BYTE)
RENT_NO2	NUMBER
BUS_CODE	NUMBER

 * Room
BOOKING_NO	NUMBER
BOOKING_PRODUCT	VARCHAR2(100 BYTE)
BOOKING_DATE	DATE
BOOKING_MODIFY	DATE
BOOKING_ADDRESS	VARCHAR2(100 BYTE)
BOOKING_PAY	VARCHAR2(20 BYTE)
BOOKING_NUMBER	NUMBER
BOOKING_PHONE	VARCHAR2(20 BYTE)
BOOKING_TRV	DATE
US_NO	VARCHAR2(15 BYTE)
HOTEL_NO	NUMBER
BUS_CODE	NUMBER

 * Tour
BOOKING_NO	NUMBER
BUS_NAME	VARCHAR2(100 BYTE)
PAY_NAME	VARCHAR2(100 BYTE)
BOOKING_DATE	DATE
BOOKING_MODIFY	DATE
BOOKING_ADDRESS	VARCHAR2(100 BYTE)
BOOKING_PAY	VARCHAR2(20 BYTE)
BOOKING_NUMBER	NUMBER
BOOKING_PHONE	VARCHAR2(20 BYTE)
BOOKING_TRV	DATE
US_NO	VARCHAR2(15 BYTE)
PRO_NO	VARCHAR2(30 BYTE)
BUS_CODE	NUMBER
 * */
}
